#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

\rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
\rm -f constant/triSurface/uav.eMesh > /dev/null 2>&1
\rm -f constant/polyMesh/boundary > /dev/null 2>&1
\rm -rf 0 > /dev/null 2>&1

cleanCase
